using System;

namespace Hidistro.Entities.Store
{
	public enum Privilege
	{
		Summary = 1000,
		SiteSettings,
		PaymentModes = 1004,
		ShippingModes,
		ShippingTemplets,
		ExpressComputerpes,
		PictureMange = 1009,
		Votes = 2009,
		Products = 3001,
		AddProducts,
		EditProducts,
		DeleteProducts,
		InStockProduct,
		UpShelfProducts,
		OffShelfProducts,
		ProductUnclassified = 3010,
		SubjectProducts,
		ProductBatchUpload,
		ProductTypes = 3017,
		AddProductType,
		EditProductType,
		DeleteProductType,
		ProductCategory,
		AddProductCategory,
		EditProductCategory,
		DeleteProductCategory,
		BrandCategories,
		ProductBatchExport,
		Orders = 4001,
		DeleteOrder,
		EditOrders,
		CofimOrderPay,
		OrderSendGoods,
		ExpressPrint,
		RemarkOrder = 4008,
		ExpressTemplates,
		Shippers,
		OrderRefundApply = 4012,
		OrderReplaceApply,
		OrderReturnsApply,
		Members = 5001,
		EditMember,
		DeleteMember,
		MemberGrades,
		AddMemberGrade,
		EditMemberGrade,
		DeleteMemberGrade,
		ClientGroup = 7007,
		ClientNew,
		ClientActivy,
		ClientSleep,
		Gifts = 8001,
		ProductPromotion,
		OrderPromotion,
		GroupBuy = 8005,
		CountDown,
		Coupons,
		SaleReport = 10001,
		OrderStatistics,
		SaleDetails,
		SaleTargets,
		ProductSaleRanking,
		ProductSaleStatistics,
		MemberRanking,
		MemberArealDistributionStatistics,
		UserIncreaseStatistics
	}
}
